export const posts = [
  { id: 1, title: 'X-Burguer', content: 'Pão, hambúrguer, queijo, alface, tomate, maionese', image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80', descricao: 'Clássico e saboroso, perfeito para qualquer momento.' },
  { id: 2, title: 'X-Salada', content: 'Pão, hambúrguer, queijo, alface, tomate, cebola, maionese', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80', descricao: 'Leve e refrescante, ideal para quem gosta de salada.' },
  { id: 3, title: 'X-Bacon', content: 'Pão, hambúrguer, queijo, bacon, alface, tomate, maionese', image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80', descricao: 'O sabor irresistível do bacon com ingredientes frescos.' },
  { id: 4, title: 'X-Egg', content: 'Pão, hambúrguer, queijo, ovo, alface, tomate, maionese', image: 'https://images.unsplash.com/photo-1523987355523-c7b5b0723c6e?auto=format&fit=crop&w=400&q=80', descricao: 'Combinação perfeita de hambúrguer com ovo.' },
  { id: 5, title: 'X-Frango', content: 'Pão, frango grelhado, queijo, alface, tomate, maionese', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80', descricao: 'Frango grelhado para quem prefere uma opção mais leve.' },
  { id: 6, title: 'X-Calabresa', content: 'Pão, calabresa, queijo, cebola, tomate, maionese', image: 'https://images.unsplash.com/photo-1464306076886-debede6a8765?auto=format&fit=crop&w=400&q=80', descricao: 'Calabresa suculenta com queijo derretido.' },
  { id: 7, title: 'X-Tudo', content: 'Pão, hambúrguer, queijo, bacon, ovo, calabresa, alface, tomate, maionese', image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80', descricao: 'Para quem quer experimentar todos os sabores em um só lanche.' },
  { id: 8, title: 'Cheeseburguer', content: 'Pão, hambúrguer, queijo cheddar, ketchup, mostarda', image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=400&q=80', descricao: 'O clássico americano com queijo cheddar.' },
  { id: 9, title: 'Hambúrguer Vegetariano', content: 'Pão, hambúrguer de soja, queijo, alface, tomate, maionese vegana', image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80', descricao: 'Opção vegetariana cheia de sabor e frescor.' },
  { id: 10, title: 'X-Catupiry', content: 'Pão, hambúrguer, queijo, catupiry, tomate, alface', image: 'https://images.unsplash.com/photo-1523987355523-c7b5b0723c6e?auto=format&fit=crop&w=400&q=80', descricao: 'Catupiry cremoso para um lanche especial.' },
  { id: 11, title: 'X-Picanha', content: 'Pão, picanha, queijo, cebola, tomate, maionese', image: 'https://images.unsplash.com/photo-1464306076886-debede6a8765?auto=format&fit=crop&w=400&q=80', descricao: 'Picanha suculenta para quem gosta de carne nobre.' },
  { id: 12, title: 'X-Coração', content: 'Pão, coração de frango, queijo, tomate, alface, maionese', image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=400&q=80', descricao: 'Coração de frango grelhado, sabor único e marcante.' },
];